layout_spectrum: 0.1783568
typography_spectrum: 0.6543871
color:
  saturation: 0.8965279
  lightness: 0.9981186
  brandStrength: 0.8854638
  rhythmicContrast: 0.7229751
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: IndyRockets
